//
//  OffersVM.swift
//  AirlineRedesign
//
//  Created by Logan Petree on 7/9/24.
//

import Foundation

class OffersVM: ObservableObject {
    @Published var destinations: [Destination] = [
        Destination(title: "Rent a Tesla", description: "Get hottest summer rental car deals with ACE! Tesla's starting at $25.00/day!", price: nil, image: "car", buttonText: "Reserve Today", buttonURL: nil),
        Destination(title: "Explore the Wisconsin Bluffs", description: "Enjoy peaceful kayaking, hotels and hikes in La Crosse!", price: 450, image: "bluffs", buttonText: "Book Now", buttonURL: ""),
        Destination(title: "Cruise your way to status", description: "Book a qualifying cruise to earn miles!", price: nil, image: "cruise", buttonText: "Book Now", buttonURL: ""),
        Destination(title: "Group Deals for Zion", description: "Get 25% off a group hike before the end of summer!", price: nil, image: "hiking", buttonText: "Claim Offer", buttonURL: nil),
    ]
}


class AirportsVM: ObservableObject {
    @Published var aiports: [Airport] = [
        Airport(code: "ALB", city: "Albany", state: "NY"),
        Airport(code: "ABQ", city: "Albuquerque", state: "NM"),
        Airport(code: "AMA", city: "Amarillo", state: "TX"),
        Airport(code: "AUA", city: "Aruba", state: "Aruba"),
        Airport(code: "ATL", city: "Atlanta", state: "GA"),
        Airport(code: "AUS", city: "Austin", state: "TX"),
        Airport(code: "BWI", city: "Baltimore/Washington", state: "MD"),
        Airport(code: "BZE", city: "Belize City", state: "Belize"),
        Airport(code: "BOI", city: "Boise", state: "ID"),
        Airport(code: "BOS", city: "Boston (Logan)", state: "MA"),
        Airport(code: "BZN", city: "Bozeman/Yellowstone", state: "MT"),
        Airport(code: "BUF", city: "Buffalo/Niagara", state: "NY"),
        Airport(code: "BUR", city: "Burbank", state: "CA"),
        Airport(code: "CUN", city: "Cancun", state: "Mexico"),
        Airport(code: "CHS", city: "Charleston", state: "SC"),
        Airport(code: "CLT", city: "Charlotte", state: "NC"),
        Airport(code: "MDW", city: "Chicago (Midway)", state: "IL"),
        Airport(code: "ORD", city: "Chicago (O’Hare-Terminal 5)", state: "IL"),
        Airport(code: "CVG", city: "Cincinnati", state: "OH"),
        Airport(code: "CLE", city: "Cleveland", state: "OH"),
        Airport(code: "COS", city: "Colorado Springs", state: "CO"),
        Airport(code: "CMH", city: "Columbus", state: "OH"),
        Airport(code: "CRP", city: "Corpus Christi", state: "TX"),
        Airport(code: "CZM", city: "Cozumel", state: "Quintana Roo"),
        Airport(code: "DAL", city: "Dallas (Love Field)", state: "TX"),
        Airport(code: "DEN", city: "Denver", state: "CO"),
        Airport(code: "DSM", city: "Des Moines", state: "IA"),
        Airport(code: "VPS", city: "Destin/Fort Walton Beach", state: "FL"),
        Airport(code: "DTW", city: "Detroit", state: "MI"),
        Airport(code: "ELP", city: "El Paso", state: "TX"),
        Airport(code: "EUG", city: "Eugene", state: "OR"),
        Airport(code: "FLL", city: "Fort Lauderdale", state: "FL"),
        Airport(code: "RSW", city: "Fort Myers", state: "FL"),
        Airport(code: "FAT", city: "Fresno", state: "CA"),
        Airport(code: "GCM", city: "Grand Cayman", state: "Cayman Islands"),
        Airport(code: "GRR", city: "Grand Rapids", state: "MI"),
        Airport(code: "GSP", city: "Greenville/Spartanburg", state: "SC"),
        Airport(code: "HRL", city: "Harlingen", state: "TX"),
        Airport(code: "BDL", city: "Hartford", state: "CT"),
        Airport(code: "HAV", city: "Havana", state: "Cuba"),
        Airport(code: "ITO", city: "Hilo (Hawaii Island)", state: "HI"),
        Airport(code: "HNL", city: "Honolulu (Oahu)", state: "HI"),
        Airport(code: "IAH", city: "Houston (Bush-Intercontinental)", state: "TX"),
        Airport(code: "HOU", city: "Houston (Hobby)", state: "TX"),
        Airport(code: "IND", city: "Indianapolis", state: "IN"),
        Airport(code: "JAN", city: "Jackson", state: "MS"),
        Airport(code: "JAX", city: "Jacksonville", state: "FL"),
        Airport(code: "OGG", city: "Kahului (Maui)", state: "HI"),
        Airport(code: "MCI", city: "Kansas City", state: "MO"),
        Airport(code: "KOA", city: "Kona (Hawaii Island)", state: "HI"),
        Airport(code: "LAS", city: "Las Vegas", state: "NV"),
        Airport(code: "LIR", city: "Liberia (Guanacaste)", state: "Costa Rica"),
        Airport(code: "LIH", city: "Lihue (Kauai)", state: "HI"),
        Airport(code: "LIT", city: "Little Rock", state: "AR"),
        Airport(code: "LGB", city: "Long Beach", state: "CA"),
        Airport(code: "ISP", city: "Long Island/Islip", state: "NY"),
        Airport(code: "LAX", city: "Los Angeles", state: "CA"),
        Airport(code: "SJD", city: "Los Cabos", state: "MX"),
        Airport(code: "SDF", city: "Louisville", state: "KY"),
        Airport(code: "LBB", city: "Lubbock", state: "TX"),
        Airport(code: "MHT", city: "Manchester", state: "NH"),
        Airport(code: "MEM", city: "Memphis", state: "TN"),
        Airport(code: "MIA", city: "Miami", state: "FL"),
        Airport(code: "MAF", city: "Midland/Odessa", state: "TX"),
        Airport(code: "MKE", city: "Milwaukee", state: "WI"),
        Airport(code: "MSP", city: "Minneapolis/St. Paul (Terminal 2)", state: "MN"),
        Airport(code: "MBJ", city: "Montego Bay", state: "Jamaica"),
        Airport(code: "MTJ", city: "Montrose (Telluride/Crested Butte)", state: "CO"),
        Airport(code: "MYR", city: "Myrtle Beach", state: "SC"),
        Airport(code: "BNA", city: "Nashville", state: "TN"),
        Airport(code: "NAS", city: "Nassau", state: "Bahamas"),
        Airport(code: "MSY", city: "New Orleans", state: "LA"),
        Airport(code: "LGA", city: "New York (LaGuardia)", state: "NY"),
        Airport(code: "ORF", city: "Norfolk", state: "VA"),
        Airport(code: "OAK", city: "Oakland", state: "CA"),
        Airport(code: "OKC", city: "Oklahoma City", state: "OK"),
        Airport(code: "OMA", city: "Omaha", state: "NE"),
        Airport(code: "ONT", city: "Ontario/LA", state: "CA"),
        Airport(code: "SNA", city: "Orange County/Santa Ana", state: "CA"),
        Airport(code: "MCO", city: "Orlando", state: "FL"),
        Airport(code: "PSP", city: "Palm Springs", state: "CA"),
        Airport(code: "ECP", city: "Panama City Beach", state: "FL"),
        Airport(code: "PNS", city: "Pensacola", state: "FL"),
        Airport(code: "PHL", city: "Philadelphia", state: "PA"),
        Airport(code: "PHX", city: "Phoenix", state: "AZ"),
        Airport(code: "PIT", city: "Pittsburgh", state: "PA"),
        Airport(code: "PWM", city: "Portland", state: "ME"),
        Airport(code: "PDX", city: "Portland", state: "OR"),
        Airport(code: "PVD", city: "Providence", state: "RI"),
        Airport(code: "PLS", city: "Providenciales", state: "Turks and Caicos"),
        Airport(code: "PVR", city: "Puerto Vallarta", state: "MX"),
        Airport(code: "PUJ", city: "Punta Cana", state: "DO"),
        Airport(code: "RDU", city: "Raleigh/Durham", state: "NC"),
        Airport(code: "RNO", city: "Reno/Tahoe", state: "NV"),
        Airport(code: "RIC", city: "Richmond", state: "VA"),
        Airport(code: "ROC", city: "Rochester", state: "NY"),
        Airport(code: "SMF", city: "Sacramento", state: "CA"),
        Airport(code: "SLC", city: "Salt Lake City", state: "UT"),
        Airport(code: "SAT", city: "San Antonio", state: "TX"),
        Airport(code: "SAN", city: "San Diego", state: "CA"),
        Airport(code: "SFO", city: "San Francisco", state: "CA"),
        Airport(code: "SJC", city: "San Jose", state: "CA"),
        Airport(code: "SJO", city: "San Jose", state: "Costa Rica"),
        Airport(code: "SJU", city: "San Juan", state: "PR"),
        Airport(code: "SBA", city: "Santa Barbara", state: "CA"),
        Airport(code: "SRQ", city: "Sarasota/Bradenton", state: "FL"),
        Airport(code: "SAV", city: "Savannah/Hilton Head", state: "GA"),
        Airport(code: "SEA", city: "Seattle/Tacoma", state: "WA"),
        Airport(code: "GEG", city: "Spokane", state: "WA"),
        Airport(code: "STL", city: "St. Louis", state: "MO"),
        Airport(code: "HDN", city: "Steamboat Springs (Hayden)", state: "CO"),
        Airport(code: "SYR", city: "Syracuse", state: "NY"),
        Airport(code: "TPA", city: "Tampa", state: "FL"),
        Airport(code: "TUS", city: "Tucson", state: "AZ"),
        Airport(code: "TUL", city: "Tulsa", state: "OK"),
        Airport(code: "IAD", city: "Washington (Dulles)", state: "DC"),
        Airport(code: "DCA", city: "Washington (Reagan National)", state: "DC"),
        Airport(code: "PBI", city: "West Palm Beach", state: "FL"),
        Airport(code: "ICT", city: "Wichita", state: "KS")
    ]
    
    
}
